### ISSUE TITLE
Should this lib replace the core http lib?

### ISSUE THREAD

**Issue by naxmefy** [iefserge/eshttp#12]
Heyho,

should this lib replace the core http lib? If yes, why you didn't copied the API from the core module? 

If not - what else?

**Comment by iefserge** [comment]
Not really, this is an alternative to core lib, but not really replacing it. It's pretty low level also, for example, no stream wrappers, allows caching and reusing http response buffers.

**Comment by naxmefy** [comment]
sry for late response...

the reason for my question is simple - "Why should we use eshttp in replace of common frameworks"

The question "should we use both?" is unimportant here...

If you had made a similar api the common frameworks maybe had a good reason to change http with eshttp

"i goona close the issue"
