### ISSUE TITLE
How to use custom backends? 

### ISSUE THREAD

**Issue by darkyen** [iefserge/eshttp#3]
I think that should be mentioned in the docs, because of that this library becomes extremely portable (I am using it for cordova apps which talk to IoT devices both do not have the net module from node but instead use custom backends). I am happy to write examples :-)

**Comment by iefserge** [comment]
Yeah, good idea to add it to docs. This is the code I'm using to setup backend for node https://github.com/iefserge/eshttp/blob/master/index-node.js, for custom it would be something like (can probably be made nicer :) )

``` js
require('eshttp/lib/backend').setBackend(backend);
var eshttp = require('eshttp/lib/eshttp');
```

where backend is the object that has all the platform-dependent socket functions like so https://github.com/iefserge/eshttp/blob/master/backend/backend-node.js. It needs to be able to create server/client sockets, send/receive data etc.

**Comment by darkyen** [comment]
Currently I do this (read that in index)

``` javascript
// If cordova is defined use our
// custom backend over this one.
if( cordova ){
  const backend =  require('eshttp/lib/backend');
  const chromeBackend = require('./backends/chrome-tcp');
  backend.setBackend(chromeBackend);
}else {
  const backend =  require('eshttp/lib/backend');
  const nodeBackend =  require('eshttp/backends/node');
  backend.setBackend(nodeBackend);
}

// Importing it at the end is most important
const eshttp = require('eshttp');
```

I was thinking of creating a repo / gist with use of chrome's cordova tcp as an example to host a server, expect that by today :D cheers for the awesome library!

**Comment by darkyen** [comment]
https://gist.github.com/darkyen/380012c4209407c5587d - Here is my implementation of a backend, over chrome.sockets.tcp for backend. Review maybe ?
